# GitHub Dependency Review Configuration

# Fail the action if any vulnerabilities are found with these severities
fail-on-severity: 
  - critical
  - high

# Fail if any licenses are detected that are in this list
deny-licenses:
  - "GPL-2.0"
  - "GPL-3.0" 
  - "AGPL-1.0"
  - "AGPL-3.0"
  - "LGPL-2.0"
  - "LGPL-2.1"
  - "LGPL-3.0"

# Allow these licenses explicitly
allow-licenses:
  - "MIT"
  - "Apache-2.0"
  - "BSD-2-Clause"
  - "BSD-3-Clause"
  - "ISC"
  - "Unlicense"
  - "CC0-1.0"

# Fail if dependencies are found with these licenses
fail-on-licenses: 
  - "GPL-2.0"
  - "GPL-3.0"
  - "AGPL-1.0" 
  - "AGPL-3.0"

# Allow dependencies from these sources
allow-ghsas:
  - GHSA-xxxx-xxxx-xxxx  # Example: allow specific advisory if needed

# Block dependencies from these sources  
deny-ghsas:
  - GHSA-yyyy-yyyy-yyyy  # Example: block specific advisory

# Set vulnerability score threshold (0-10, where 10 is most severe)
vulnerability-check: true
fail-on-scopes:
  - runtime
  - development

# Allow certain vulnerable packages (use sparingly)
allow-dependencies-licenses: []

# Comment on PR with summary
comment-summary-in-pr: true

# Base branch to compare against
base-ref: ${{ github.event.pull_request.base.ref }}

# Head branch to compare  
head-ref: ${{ github.event.pull_request.head.ref }}