version: '3.8'

services:
  frontend:
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"

  backend:
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./books:/books
      - ./audio:/audio
    ports:
      - "5001:5000"

  crawler:
    volumes:
      - ./crawler:/app
      - /app/node_modules
      - ./books:/books
    ports:
      - "3001:3001"

  parser:
    volumes:
      - ./parser:/app
      - /app/node_modules
      - ./books:/books
      - ./audio:/audio
    ports:
      - "3002:3002"

  tts-api:
    volumes:
      - ./tts-api:/app
      - ./audio:/audio
      - ./tts_models_cache:/root/.cache # Local cache for TTS models
    ports:
      - "8000:8000"

  postgres:
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  redis:
    volumes:
      - ./data/redis:/data
    ports:
      - "6380:6379"

  nginx:
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
      - ./audio:/var/www/audio:ro
    ports:
      - "80:80"
      - "443:443"

volumes:
  postgres_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./data/postgres
  redis_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./data/redis
  books_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./books
  audio_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./audio
  tts_models:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./tts_models_cache
