version: '3.8'

services:
  # Only the essential services for testing crawler
  postgres:
    image: postgres:15-alpine
    container_name: audiobook-postgres-dev
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=audiobook
      - POSTGRES_PASSWORD=audiobook123
      - POSTGRES_DB=audiobook_db
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - audiobook-network

  redis:
    image: redis:7-alpine
    container_name: audiobook-redis-dev
    ports:
      - "6379:6379"
    networks:
      - audiobook-network

  crawler:
    build:
      context: ./crawler
      dockerfile: Dockerfile
    container_name: audiobook-crawler-dev
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - DATABASE_URL=postgresql://audiobook:audiobook123@postgres:5432/audiobook_db
      - REDIS_URL=redis://redis:6379
      - BOOKS_PATH=/books
      - LOG_LEVEL=info
    volumes:
      - ./crawler:/app
      - /app/node_modules
      - ./books:/books
    depends_on:
      - postgres
      - redis
    networks:
      - audiobook-network

networks:
  audiobook-network:
    driver: bridge