apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: audiobook
  labels:
    app: audiobook
    component: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: audiobook
      component: frontend
  template:
    metadata:
      labels:
        app: audiobook
        component: frontend
    spec:
      containers:
      - name: frontend
        image: audiobook/frontend:latest
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        - name: NEXT_PUBLIC_API_URL
          valueFrom:
            configMapKeyRef:
              name: audiobook-config
              key: BACKEND_URL
        - name: NEXT_PUBLIC_AUTH_URL
          valueFrom:
            configMapKeyRef:
              name: audiobook-config
              key: AUTH_SERVICE_URL
        envFrom:
        - configMapRef:
            name: audiobook-config
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "1"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 30
      initContainers:
      - name: wait-for-backend
        image: busybox:1.35
        command: ['sh', '-c', 'until nc -z backend-service 5000; do echo waiting for backend; sleep 2; done;']
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: audiobook
  labels:
    app: audiobook
    component: frontend
spec:
  selector:
    app: audiobook
    component: frontend
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-hpa
  namespace: audiobook
  labels:
    app: audiobook
    component: frontend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80