apiVersion: v1
kind: Secret
metadata:
  name: audiobook-secrets
  namespace: audiobook
  labels:
    app: audiobook
type: Opaque
stringData:
  # Database credentials
  DB_USER: "audiobook"
  DB_PASSWORD: "audiobook123"
  DATABASE_URL: "postgresql://audiobook:audiobook123@postgres-service:5432/audiobook_db"
  
  # Redis password (if needed)
  REDIS_PASSWORD: ""
  REDIS_URL: "redis://redis-service:6379"
  
  # JWT secrets
  JWT_SECRET: "your-very-secure-jwt-secret-key-here-change-in-production"
  JWT_REFRESH_SECRET: "your-very-secure-refresh-secret-key-here-change-in-production"
  
  # Security configuration
  CSP_REPORT_URI: "https://your-domain.com/api/csp-report"
  AUDIO_CDN_URL: "https://your-audio-cdn.com"
  API_URL: "https://api.your-domain.com"
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: audiobook
  labels:
    app: audiobook
    component: postgres
type: Opaque
stringData:
  POSTGRES_USER: "audiobook"
  POSTGRES_PASSWORD: "audiobook123"
  POSTGRES_DB: "audiobook_db"
---
apiVersion: v1
kind: Secret
metadata:
  name: ssl-certificates
  namespace: audiobook
  labels:
    app: audiobook
    component: ssl
type: kubernetes.io/tls
data:
  # Base64 encoded SSL certificates
  # Replace with your actual certificates
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCi4uLgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCi4uLgotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0t