version: '3.8'

secrets:
  jwt_secret:
    file: ./secrets/jwt_secret
  postgres_password:
    file: ./secrets/postgres_password
  redis_password:
    file: ./secrets/redis_password
  admin_password:
    file: ./secrets/admin_password

services:
  auth:
    secrets:
      - jwt_secret
      - postgres_password
      - admin_password
    environment:
      JWT_SECRET_FILE: /run/secrets/jwt_secret
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      ADMIN_PASSWORD_FILE: /run/secrets/admin_password

  backend:
    secrets:
      - jwt_secret
      - postgres_password
      - redis_password
    environment:
      JWT_SECRET_FILE: /run/secrets/jwt_secret
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      REDIS_PASSWORD_FILE: /run/secrets/redis_password

  frontend:
    secrets:
      - jwt_secret
    environment:
      JWT_SECRET_FILE: /run/secrets/jwt_secret

  postgres:
    secrets:
      - postgres_password
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password

  redis:
    secrets:
      - redis_password
    command: redis-server --requirepass-file /run/secrets/redis_password
